### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [ExplosBlue/CoinKiller#62]
I have made a Flatpak package for CoinKiller that I will publish on Flathub.  You need this files to build the package.

io.github.Arisotura.CoinKiller.yaml
```yaml
id: io.github.Arisotura.CoinKiller
runtime: org.kde.Platform
runtime-version: 6.4
sdk: org.kde.Sdk
command: CoinKiller
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=ipc

modules:
  - name: CoinKiller
    buildsystem: qmake
    post-install:
      - install -Dm755 CoinKiller -t $FLATPAK_DEST/CoinKiller
      - cp -r coinkiller_data $FLATPAK_DEST/CoinKiller
      - mkdir -p $FLATPAK_DEST/bin
      - ln -s $FLATPAK_DEST/CoinKiller/CoinKiller $FLATPAK_DEST/bin/CoinKiller
      - install -Dm644 coinkiller_data/icons/logo.png $FLATPAK_DEST/share/icons/hicolor/512x512/apps/$FLATPAK_ID.png
      - install -Dm644 $FLATPAK_ID.desktop -t $FLATPAK_DEST/share/applications
      - install -Dm644 $FLATPAK_ID.metainfo.xml -t $FLATPAK_DEST/share/metainfo
    sources:
      - type: archive
        archive-type: tar-gzip
        url: https://api.github.com/repos/Arisotura/CoinKiller/tarball/v1.1
        sha256: 81e43517845f143ccbd2ea92a42d51d1370a2c241b7237dcc2f298aa1c9dae69
        x-checker-data:
            type: json
            url: https://api.github.com/repos/Arisotura/CoinKiller/releases/latest
            version-query: .tag_name
            url-query: .tarball_url
            is-main-source: true
      - type: file
        path: io.github.Arisotura.CoinKiller.desktop
      - type: file
        path: io.github.Arisotura.CoinKiller.metainfo.xml
```

io.github.Arisotura.CoinKiller.desktop
```desktop
# Created with jdDesktopEntryEdit 1.0
[Desktop Entry]
Type=Application
Name=CoinKiller
Comment=A level editor for NSMB2
Icon=io.github.Arisotura.CoinKiller
TryExec=CoinKiller
Exec=CoinKiller
Categories=Game;Qt;
Keywords=Editor;Mario;Nintendo;3DS;Hack;
SingleMainWindow=true
```

```xml
<?xml version='1.0' encoding='utf-8'?>
<component type="desktop">
  <!--Created with jdAppStreamEdit 6.0-->
  <id>io.github.Arisotura.CoinKiller</id>
  <name>CoinKiller</name>
  <summary>A level editor for NSMB2</summary>
  <developer_name>Arisotura</developer_name>
  <launchable type="desktop-id">io.github.Arisotura.CoinKiller.desktop</launchable>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-3.0</project_license>
  <description>
    <p>A level editor for NSMB2. Uses Qt6 and is coded in C++</p>
    <p>CoinKiller requires a dump of NSMB2</p>
  </description>
  <releases>
    <release version="v1.1" date="2023-01-17" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v1.1</url>
      <description>
        <ul>
          <li>Fix bounding tooltips</li>
        </ul>
      </description>
    </release>
    <release version="v1.0" date="2022-06-26" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v1.0</url>
    </release>
    <release version="v0.15" date="2020-12-09" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.15</url>
    </release>
    <release version="v0.14" date="2020-07-01" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.14</url>
    </release>
    <release version="v0.13" date="2020-06-26" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.13</url>
    </release>
    <release version="v0.12" date="2020-05-28" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.12</url>
    </release>
    <release version="v0.11" date="2020-02-28" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.11</url>
    </release>
    <release version="v0.10" date="2019-08-19" type="stable">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.10</url>
    </release>
    <release version="v0.9" date="2018-12-29" type="development">
      <url>https://github.com/Arisotura/CoinKiller/releases/tag/v0.9</url>
    </release>
  </releases>
  <url type="homepage">https://github.com/Arisotura/CoinKiller</url>
  <url type="bugtracker">https://github.com/Arisotura/CoinKiller/issues</url>
  <categories>
    <category>Game</category>
    <category>Qt</category>
  </categories>
  <recommends>
    <control>pointing</control>
    <control>keyboard</control>
  </recommends>
  <content_rating type="oars-1.1"/>
  <provides>
    <binary>CoinKiller</binary>
  </provides>
  <keywords>
    <keyword>Editor</keyword>
    <keyword>Mario</keyword>
    <keyword>Nintendo</keyword>
    <keyword>3DS</keyword>
    <keyword>Hack</keyword>
  </keywords>
</component>
```
